configuration: Release

before_build:
  - dotnet restore Drogueria-El-Cafetero/Codigos/Login/Drogueria_Elcafetero.sln
build:
  verbosity: minimal
  publish_wap: true

build_script:
  - dotnet publish Drogueria-El-Cafetero/Codigos/Login/Drogueria_Elcafetero.sln -c Release -o out
